### ISSUE TITLE
Player dosent move

### ISSUE THREAD

**Issue by Schattenpfote** [0xDrMoe/TownofHost-Enhanced#737]
Original Poster: eispfote42
Version: 1.5.2
Original Date of Issue: March 10,2024
Fix Attempted Before? No
Map: All
Reproducible? Yes
Description/Additional Notes: If I host a game,everything works,but in a round,I can move,but other player doesnt in my view.They move in their view, but the other players (including me) don't move with them.
Thats with all people I tried,my friends,randoms etc.

**Comment by MargaretTheFool** [comment]
Taken directly from the discord:

# ⚠️ TOHE Compatibility Notice ⚠️ 

## It's been a few days, so let me keep you all updated since everyone seems to be CONSTANTLY asking this question.

## No one is moving when I host a lobby, what do I do?
### Wait. We have identified the issues with our modded protocol and are waiting on Innersloth to push a fix. We are actively in contact with them, but do NOT have an ETA.

### Summary: We know there's a problem with TOHE. We don't know how long it'll be for IS to fix this issue, it is out of our control and is a problem on ALL *TOH* based mods.

### Note, you can play on MNA, MEU, MAS - EVERYONE must be on, BUT friendcode-related fetures will NOT work.

Thanks, @ everyone - PLEASE let people know about this *every time they ask*.

As always, stay safe
\- Moe

**Comment by Tommy-XL** [comment]
It's best for you to log into discord to always know the current status of the problem:
https://discord.gg/tohe

**Comment by Tommy-XL** [comment]
Servers now fixed
