### ISSUE TITLE
cant connect to api servers

### ISSUE THREAD

**Issue by Hmmmmmfate** [0xDrMoe/TownofHost-Enhanced#841]
for some reason every time I boot up tohe among us It says I can't connect to the api servers. PLS HELP.

**Comment by TheDiamondStar** [comment]
If you are playing the mod on Steam, you need to have the steam app opened so that it can connect your account. For Epic Games, you will need to have the mod in the same files as vanilla Among Us. Don't worry, it won't mess up anything, because there is an option to change to vanilla in settings. Hope this helps!
